dist: xenial
services:
- docker

env: # for allow_failures: https://docs.travis-ci.com/user/customizing-the-build/
matrix:
  include:

  - language: go
    name: "Build in Docker (docs/installation.rst)"
    script:
    - sudo docker build -t zrepl_build -f build.Dockerfile .
    - |
      sudo docker run -it --rm \
        -v "${PWD}:/go/src/github.com/zrepl/zrepl" \
        --user "$(id -u):$(id -g)" \
        zrepl_build make vendordeps release

  - &zrepl_build_template
    language: go
    go_import_path: github.com/zrepl/zrepl
    before_install:
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
        - echo "6003de742ea3fcf703cfec1cd4a3380fd143081a2eb0e559065563496af27807  protoc-3.6.1-linux-x86_64.zip" | sha256sum -c
        - sudo unzip -d /usr protoc-3.6.1-linux-x86_64.zip
        - ./lazy.sh godep
        - make vendordeps
    script:
      - make
      - make vet
      - make test
      - make lint
      - make artifacts/zrepl-freebsd-amd64
      - make artifacts/zrepl-linux-amd64
      - make artifacts/zrepl-darwin-amd64
    go:
    - "1.11"

  - <<: *zrepl_build_template
    go:
    - "1.15.x"

  - <<: *zrepl_build_template
    go:
    - "master"

  - &zrepl_docs_template
    language: python
    python:
    - "3.4"
    install:
    - sudo apt-get install libgirepository1.0-dev
    - pip install -r docs/requirements.txt
    script:
    - make docs
  - <<: *zrepl_docs_template
    python:
    - "3.5"
  - <<: *zrepl_docs_template
    python:
    - "3.6"
  - <<: *zrepl_docs_template
    python:
    - "3.7"

  allow_failures:
  - <<: *zrepl_build_template
    go:
    - "master"
